parameters:

services:
  _defaults:
    public:        true


##### Http Listener Kernel

  austral.http.doctrine.listener:
    class:        Austral\HttpBundle\Listener\DoctrineListener
    arguments:    [ "@austral.http.domains.management" ]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  austral.http.listener:
    class:          Austral\HttpBundle\Listener\HttpListener
    arguments:
      - "@service_container"
      - "@event_dispatcher"
      - "@austral.http.config"
      - "@austral.http.request"
      - "@austral.tools.debug"
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: initRequest, priority: 30 }
      - { name: kernel.event_listener, event: kernel.request, method: onRequest }
      - { name: kernel.event_listener, event: kernel.controller, method: onController }
      - { name: kernel.event_listener, event: kernel.response, method: onResponse, priority: -2048 }
      - { name: kernel.event_listener, event: kernel.exception, method: onException, priority: 2048 }
      - { name: kernel.event_listener, event: kernel.finish_request, method: onFinishRequest }

  austral.http.entity_mapping.listener:
    class:        Austral\HttpBundle\Listener\EntityMappingListener
    tags:
      - { name: kernel.event_listener, event: "austral.event.entity.initialise.mapping", method: mapping }

##### Http Services
  austral.http.request:
    class:          Austral\HttpBundle\Services\HttpRequest
    arguments:      [ "@austral.http.config" ]

  austral.http.domains.management:
    class:          Austral\HttpBundle\Services\DomainsManagement
    arguments:
      - "@austral.entity.mapping"
      - "@austral.entity_manager.domain"
      - "@austral.http.request"
      - "@austral.tools.debug"

##### Entity Manager Listener
  austral.http.entity_manager.listener:
    class:          Austral\HttpBundle\Listener\EntityManagerListener
    arguments:      ["@austral.entity.mapping", "@austral.http.domains.management", "@austral.http.request"]
    tags:
      - { name: kernel.event_listener, event: "austral.entity_manager.duplicate", method: duplicateUrlParameter }

##### Configuration
  austral.http.config:
    class:      Austral\HttpBundle\Configuration\HttpConfiguration
    arguments:  [ "%austral_http%" ]

##### Domain Entity Manager
  austral.entity_manager.domain:
    class:          Austral\HttpBundle\EntityManager\DomainEntityManager
    arguments:      [ "@doctrine.orm.entity_manager",  "@event_dispatcher", "%austral.entity.domain.class%" ]