austral_http:
  default_language:         "en"
  languages:
    - fr
    - en

  protocol:                 https

  env:
    current:                prod
    list:
      -                     prod

  compression_gzip:
    admin:                  true
    website:                true
    other:                  true