austral_http:
  default_language:         "en"
  languages:
    - fr
    - en

  protocol:                 https

  compression_gzip:
    admin:                  true
    website:                true
    other:                  true