austral_http:
  default_language:         "en"
  protocol:                 https

  compression_gzip:
    admin:                  true
    website:                true
    other:                  true